---
settings:
  name: BlueXP replication
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de replicación de BlueXP
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Más información sobre la replicación de BlueXP
      url: "/concept-replication.html"
    - title: Configure la replicación de datos
      url: "/task-replicating-data.html"
  - title: Gestionar la replicación de datos
    url: "/task-managing-replication.html"
  - title: Leer más
    entries:
    - title: Obtenga información acerca de las políticas de replicación
      url: "/concept-replication-policies.html"
    - title: Obtenga más información sobre las políticas de backup
      url: "/concept-backup-policies.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
